### ISSUE TITLE
primeorder 0.13.4 update breaks p384 0.13.0 builds 

### ISSUE THREAD

**Issue by cart** [RustCrypto/elliptic-curves#984]
The `primeorder` 0.13.4 update broke `p384` v0.13.0 builds. There were changes to `p384` on master branch to get it to build with `primeorder` 0.13.4. `primeorder` 0.13.4 should probably be yanked to avoid breakage. The dirtier option is doing a `0.13.1` patch release for `p384` containing the fix, but this wouldn't help other consumers of `primeorder`.

This breaks bevy builds so fixing this is a high priority for us.

@tarcieri

**Comment by tarcieri** [comment]
What's the build failure?

**Comment by cart** [comment]
```
    Compiling p384 v0.13.0
error[E0277]: the trait bound `FieldElement: elliptic_curve::ops::Invert` is not satisfied
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/p384-0.13.0/src/arithmetic.rs:40:25
   |
40 |     type FieldElement = FieldElement;
   |                         ^^^^^^^^^^^^ the trait `elliptic_curve::ops::Invert` is not implemented for `FieldElement`
   |
   = help: the following other types implement trait `elliptic_curve::ops::Invert`:
             Scalar
             BlindedScalar<C>
             elliptic_curve::NonZeroScalar<C>
note: required by a bound in `primeorder::PrimeCurveParams::FieldElement`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primeorder-0.13.4/src/lib.rs:38:11
   |
37 |     type FieldElement: PrimeField<Repr = FieldBytes<Self>>
   |          ------------ required by a bound in this associated type
38 |         + Invert<Output = CtOption<Self::FieldElement>>;
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `PrimeCurveParams::FieldElement`
```

From our CI builds of `cargo-udeps`

https://github.com/bevyengine/bevy/actions/runs/6884781565/job/18727900621#step:5:486

**Comment by tarcieri** [comment]
Aah, thanks

**Comment by tarcieri** [comment]
I've released v0.13.6 as a replacement which should hopefully address this problem
